sudo: false

language: elixir
elixir: 1.5.0
otp_release: 20.1

cache:
  directories:
    - sysconfcpus
    - deps
    - $HOME/.npm
    - web/node_modules

addons:
  - postgresql: "9.5"
  - chrome: stable
  - apt:
    packages:
      - libssh2-1-dev
      - cmake


os:
  - linux

env:
  global:
    - LIBGIT2=~/libgit2/_install/
    - LD_LIBRARY_PATH=~/libgit2/_install/lib
    - JOBS=1

before_install:
  - "./test/scripts/travisbuild.sh"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm config set spin false
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=1.19.0 -y
  - rustc --version
  - cargo --version

install:
  - travis_retry npm install -g bower
  - cd web
  - travis_retry npm install
  - travis_retry bower install
  - cd ../
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - cp config/travis.exs config/test.exs
script:
  - mix test
  #- cd web
  #- ./node_modules/ember-cli/bin/ember test
