sudo: false

language: elixir
elixir: 1.4.0

cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - sysconfcpus
    - deps

addons:
  - postgresql: "9.5"

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm-use elm-test@0.18.3
  - elm-use $ELM_VERSION
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - cd apps/gitwerk_web/assets/
  - travis_retry elm-package install --yes
  - cd tests
  - travis_retry elm-package install --yes
  - cd ../../../../
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - cp apps/gitwerk_data/config/travis.exs apps/gitwerk_data/config/test.exs
script:
  - mix test
  - cd apps/gitwerk_web/assets/
  - elm test
