sudo: false

language: elixir
elixir: 1.5.0
otp_release: 20.1

cache:
  directories:
    - sysconfcpus
    - deps

addons:
  - postgresql: "9.5"
  - apt:
    packages:
      - libssh2-1-dev
      - cmake


os:
  - linux

env:
  global:
    - LIBGIT2=~/libgit2/_install/
    - LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
  - "./test/scripts/travisbuild.sh"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - cd web
  - travis_retry npm install
  - cd ../
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - cp config/travis.exs config/test.exs
script:
  - mix test
  - cd assets/elm-app
  - ember test
